### ISSUE TITLE
quiet

### ISSUE THREAD

**Issue by romainfrancois** [romainfrancois/nothing#3]
This makes a lot of noise for nothing: 

```
> require(nothing)
Loading required package: nothing
unloading 'methods' package ...
Failed with error:  ‘invalid 'pos' argument’
```

**Comment by leeper** [comment]
Wrap it in `suppressMessages`?

**Comment by romainfrancois** [comment]
I get: 

```
> suppressMessages( require(nothing) )
Failed with error:  ‘invalid 'pos' argument’
```

So there still is a problem, but more importantly, it is too much work to have to type suppressMessages for nothing.

**Comment by daroczig** [comment]
You can also divert the R output to e.g. `/dev/null` (or wrap in `capture.output`) to suppress the "Failed with error" msg `cat` by `require` for a perfect user experience :)

**Comment by romainfrancois** [comment]
Would you do a pull request ?

**Comment by daroczig** [comment]
Sure, I'll be happy to do that in a few days.
