### ISSUE TITLE
Added flexibility with unloading packages 

### ISSUE THREAD

**Issue by konradzdeb** [romainfrancois/nothing#7]
I would suggest that in the code:

```r
pkgs <- setdiff(loadedNamespaces(), "base")
```

- the string default `"base"` is replaced with choice between keeping the `base` package only **or** all tha packages usually loaded when R starts.

- It's further extended with additional string representing packages that the one wishes to keep: i.e. *unload everything other than usual stuff and `dplyr` / `tidyr`*

**Comment by romainfrancois** [comment]
That's not compatible with the joke of the package.

**Comment by kendonB** [comment]
I believe I have a real use case for this package. I am running a shiny-server app on a machine that I don't have sudo access to. I am running into a bug that I believe arises from the R session loading old versions of some packages from the site-library before I have a chance to switch .libPaths() to something I can access. I can't think of another way to elegantly achieve what I want other than using this super-useful-and-not-a-joke package. It would be nice to have an almostnothing package that keeps the base, graphics, stats, methods, etc packages that usually get loaded when R does.
